### ISSUE TITLE
Image data of album covers

### ISSUE THREAD

**Issue by leod** [mdeff/fma#51]
Hi, the FMA dataset looks amazing, thank you so much for sharing this!

I'm planning a research project that will involve multimodal models trained on album covers as well as the audio signal of tracks from the respective albums. Does FMA include cover art?

If I understand correctly from the FMA paper, cover art is not yet included. Quoting from the discussion section:
>  Cover images for tracks, albums, and artists are another public asset which may be of interest.

From what I can tell on the freemusicarchive.org website, albums seem to usually (always?) come with a cover image. I think I might be able to automatically download these based on the album names in the FMA dataset. However, I'm wondering if there is a better way. I would appreciate any recommendation.

**Comment by leod** [comment]
It seems that [`webapi.ipynb`](https://github.com/mdeff/fma/blob/master/webapi.ipynb) might basically answer my question already.

**Comment by mdeff** [comment]
Thanks for the kind words!

Cover art is indeed not included and should be easy to download automatically. You'll find URLs in the `track_image_file` column of `raw_tracks.csv`, `album_image_file` column of `raw_albums.csv`, and `artist_image_file` column of `raw_artists.csv`.

Since FMA got acquired it seems that the URLs have to be updated like the following:
* <https://freemusicarchive.org/file/images/artists/AWOL_-_2009113014453413.jpg> ->
  <https://freemusicarchive.org/image?file=images/artists/AWOL_-_2009113014453413.jpg&width=290&height=290&type=image>
* <https://freemusicarchive.org/file/images/albums/AWOL_-_AWOL_-_A_Way_Of_Life_-_2009113011911435.jpg> -> 
  <https://freemusicarchive.org/image?file=images/albums/AWOL_-_AWOL_-_A_Way_Of_Life_-_2009113011911435.jpg&width=290&height=290&type=image>
* <https://freemusicarchive.org/file/images/tracks/Clockcleaner_-_03_-_When_My_Ship_Comes_In_-_2009113051004857.jpg> ->
  <https://freemusicarchive.org/image?file=images/tracks/Clockcleaner_-_03_-_When_My_Ship_Comes_In_-_2009113051004857.jpg&width=290&height=290&type=track>

I don't know if other combinations of `width=290&height=290` could work.

Please share your work if you collect the covers. :) (Especially as the future of the FMA website seems uncertain.)

**Comment by leod** [comment]
Woohoo, thank you for the prompt and helpful response!

I've written a [script](https://github.com/leod/aural-travels/blob/main/tools/prepare_album_data.py) for downloading the image data.

I've taken a first look at the image data -- so far it looks fine. Luckily, the download seems to have succeeded for many albums (13509/14854, i.e. 90.95%). I'm making the cover images available here for now: https://leod.org/data/fma_album_covers.zip (541 MiB).
(I cannot guarantee that this URL will be available in the long run.)

I will close the ticket, thanks again!

**Comment by mdeff** [comment]
Thanks for sharing! I've saved it and will take care of the long-term hosting if there's demand. :)

You mention 13,509 covers but there are 14,225 images in your zip file. What's the difference?

**Comment by leod** [comment]
Great, thank you!

Regarding the difference: I've downloaded the images for all rows of `raw_albums.csv` where available. This yielded 14,225 images. However, only 13,509 of these raw albums actually have at least one track in `tracks.csv`, so these are the ones I've mentioned. I've included the rest of the images for completeness, but they are unlikely to be useful. Hope this adds up.

**Comment by mdeff** [comment]
It does! Thanks for precising.
